### ISSUE TITLE
PodSpread: Get spread rate from annotations

### ISSUE THREAD

**Issue by ebiiim** [waok8s/wao-scheduler#2]
https://github.com/Nedopro2022/wao-scheduler-v2/blob/1742bb153d5fafb7bebc73b38e28a3d893e28a1d/plugins/podspread/podspread.go#L225

name: `podspread/rate` (in ReplicaSet)
value: `float64`

e.g.
```yaml
metadata:
  annotations:
    podspread/rate: "0.25"
}
```
